"""One immutable share card per (trading_date, lang).

Written on the first share of a trading day and never updated: every later
viewer of a forwarded link sees exactly what the sharer saw. That immutability
is also what makes `Cache-Control: immutable` literally true on the rendered
image — a past date's card cannot change.

Stores the DATA, not the rendered PNG. Regeneration is deterministic, and
~3 KB x 2 languages x 252 trading days is ~1.5 MB/year; PNGs would be ~50
MB/year on the Postgres disk (trap #10).

`String(36)` primary key per the backend rules — never `Uuid(as_uuid=False)`,
which stores unhyphenated hex in SQLite and breaks raw-SQL lookups.
"""
from __future__ import annotations

from datetime import datetime
from typing import Optional

from sqlalchemy import DateTime, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column

from app.db.session import Base


class DailyCard(Base):
    __tablename__ = "daily_cards"
    # The race guard: two users sharing in the same second both find no card,
    # both generate, and one insert loses. The loser reads the winner's row
    # instead of paying a second LLM call and writing a divergent card.
    __table_args__ = (UniqueConstraint("trading_date", "lang", name="uq_daily_card_date_lang"),)

    id: Mapped[str] = mapped_column(String(36), primary_key=True)
    # ISO date of the CLOSE the card describes — not the day it was generated.
    trading_date: Mapped[str] = mapped_column(String(10), nullable=False, index=True)
    lang: Mapped[str] = mapped_column(String(8), nullable=False)
    # JSON as TEXT: SQLite has no JSONB and the column is read whole, never
    # queried into. `is_sqlite` branching in migrations.py picks the real type.
    payload: Mapped[str] = mapped_column(Text, nullable=False, default="{}")
    copy: Mapped[str] = mapped_column(Text, nullable=False, default="{}")
    # Which model wrote it. A card generated by a model we later change should
    # be identifiable without archaeology.
    model: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)
    created_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime, default=datetime.utcnow
    )
